CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT UNIQUE, nickname TEXT, password TEXT);
CREATE TABLE households (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE access (householdid INTEGER REFERENCES households ON DELETE CASCADE, userid INTEGER REFERENCES users ON DELETE CASCADE, admin BOOLEAN DEFAULT FALSE);
CREATE TABLE tasks (id SERIAL PRIMARY KEY, householdid INTEGER REFERENCES households ON DELETE CASCADE, name TEXT, description TEXT, deadline DATE, complete BOOLEAN DEFAULT FALSE);
CREATE TABLE assignees (taskID INTEGER REFERENCES tasks ON DELETE CASCADE, userID INTEGER REFERENCES users ON DELETE CASCADE);

